services:

  postgres:
    image: postgres:18

    container_name: inventory-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: inventory
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: